[API](../README.md) / [\<internal\>](../modules/internal_.md) / ["/home/szgy/src/dd/mapeo-core-next/src/local-peers"](../modules/internal_.__home_szgy_src_dd_mapeo_core_next_src_local_peers_.md) / UnknownPeerError

# Class: UnknownPeerError

[\<internal\>](../modules/internal_.md).["/home/szgy/src/dd/mapeo-core-next/src/local-peers"](../modules/internal_.__home_szgy_src_dd_mapeo_core_next_src_local_peers_.md).UnknownPeerError

## Hierarchy

- `Error`

  ↳ **`UnknownPeerError`**

## Table of contents

### Constructors

- [constructor](internal_.__home_szgy_src_dd_mapeo_core_next_src_local_peers_.UnknownPeerError.md#constructor)

### Properties

- [name](internal_.__home_szgy_src_dd_mapeo_core_next_src_local_peers_.UnknownPeerError.md#name)

## Constructors

### constructor

• **new UnknownPeerError**(`message?`): [`UnknownPeerError`](internal_.__home_szgy_src_dd_mapeo_core_next_src_local_peers_.UnknownPeerError.md)

#### Parameters

| Name | Type |
| :------ | :------ |
| `message?` | `string` |

#### Returns

[`UnknownPeerError`](internal_.__home_szgy_src_dd_mapeo_core_next_src_local_peers_.UnknownPeerError.md)

#### Overrides

Error.constructor

#### Defined in

[src/local-peers.js:616](https://github.com/digidem/mapeo-core-next/blob/315dc9781d8d2f74f17b1fd651a3ae81272b7fac/src/local-peers.js#L616)

## Properties

### name

• **name**: `string`

#### Inherited from

Error.name

#### Defined in

[src/local-peers.js:618](https://github.com/digidem/mapeo-core-next/blob/315dc9781d8d2f74f17b1fd651a3ae81272b7fac/src/local-peers.js#L618)
